### ISSUE TITLE
[BUG] empty username/group fail without output

### ISSUE THREAD

**Issue by erickmartins** [TheJacksonLaboratory/jax-omeroutils#18]
Empty username and group are read as floats, and fail [here](https://github.com/TheJacksonLaboratory/jax-omeroutils/blob/81ecf3a2a10e63f1bf3ef05e322a49416f3077fa/jax_omeroutils/intake.py#L131). Easy fix is to force these to be read as strings.

**Comment by mellertd** [comment]
that should fix it. Lets leave open until we have a chance to test

**Comment by erickmartins** [comment]
issue was fixed on commit b4769c4
