### ISSUE TITLE
Utility to get all files associated with an Image [or dataset, etc]

### ISSUE THREAD

**Issue by perlman** [TheJacksonLaboratory/jax-omeroutils#6]
A utility function to implement the following:
```
            files = [
                os.path.join("/", client_path)
                for client_path in image.getImportedImageFilePaths()['client_paths']
                ]
```

It should probably be an option to choose between the imported file path & the path within the managed repo.

**Comment by mellertd** [comment]
any suggestion on a name? `get_files`? `get_imported_files`? Or maybe `get_imported_file_paths`?

**Comment by mellertd** [comment]
Check out f969ef69e9c079bee3d48b8ffdd4899a4f4f25a4 and let me know if this works for you @perlman
